---
# This playbook prints a simple debug message
- name: Echo 
  hosts: "{{class}}"

  tasks:
  - name: Print debug message
    debug:
      msg: "{{text}}"
  - name: Creates directory
    file:
      path: /tmp/sahlovs/gradle
      state: directory
  - name: download sources
    get_url: url=https://services.gradle.org/distributions/{{gradle_version}} dest=/tmp/sahlovs/gradle/{{gradle_version}}
  - name: Extract foo.tgz into /var/lib/foo
    unarchive:
      src: /tmp/sahlovs/gradle/{{gradle_version}}
      dest: /tmp/sahlovs/gradle
      remote_src: yes
  - name: Print gradle_version
    debug:
      msg: "{{gradle_version}}"
