---

- name: Echo
  hosts: "{{host}}"
  tasks:
    - name: ansible create directory example
    file:
      path: /tmp/test/java_dns
      state: directory
      
    - name: download sources
    get_url: url=https://repo1.maven.org/maven2/dnsjava/dnsjava/3.5.0/dnsjava-3.5.0.jar dest=/tmp/test/java_dns

    - name: Print text
      debug:
        msg: "playbook123 printing a message in {{host}} "
